### PR TITLE
Adding exceptions for allowed IPs from known AWS CIDRs.

### PR DESCRIPTION
**Pull request by timifit**
Scout Suite flagged security groups allowing ingress/egress to known AWS CIDRs. This is deemed a security risk, because the static IPs are part or AWS generic pool and can technically be released and then acquired by another AWS account owner.

Setting allowances for external IPs is necessary for integration with various third parties such as Segment, Fivetran, Analytics8, etc.. In addition it allows connectivity between iFit's logical environments since VPC peering is not used.

All IPs in the Scout Suite report were reviewed and remediated by:

- Removing obsolete security groups
- Removing obsolete ingress/egress rules
- Adding all remaining IPs not resolved by the methods above to exception list

### CODE REVIEW

**Review by jonb-ifit — COMMENTED** [review]
What are these values? It looks like a security group id + a port (range) + a number? Is that number an index of an item in an ingress list? So does this depend on the order of the items in the list?

**Comment by timifit** [comment]
Unfortunately you're correct about the index-based nature of the rules.  It seems like a [design flaw](https://ifitdev.atlassian.net/wiki/spaces/DEVOPS/pages/1361773369/How+to+Create+Scout+Suite+Exceptions+and+Test+Locally#Exceptions-Design-Flaw) that we're not going to overcome.

I question whether there's value in creating an exception at all in this particular case, because the exception is completely unreliable on the next run.  Other cases like w/ the ELB exceptions those are based on an ELB instance and port 80 so the exception will "stick" to the appropriate resource.

**Comment by timifit** [comment]
I think documentation around which security group ingress/egress rules should have exceptions will be necessary so an operator can manually evaluate the results of a future run.  I don't see any other ways around it. We'll use a similar hierarchy as the native exception list but at the line item level we'll provide details that allow matching flagged IPs to our "exceptions".

The documentation should be in markdown format so it can be easily managed and reviewed with source control.

Although we could attempt to create some utility that computes the exception based on the specific IP, security group and ports involved, the utility would be at high risk of breaking on any future release of Scout Suite since there is no published schema for the complex JSON results and no expectation to maintain backwards compatibility of the data model.

**Comment by timifit** [comment]
`Not Doing` this incredibly outdated PR.

**Pull request closed without merging**
