### PR TITLE
Adding exceptions for ELB2.

### PR DESCRIPTION
**Pull request by timifit**
Scout Suite flagged ELBs (v2) for listening to port 80 which accepts unsecure HTTP requests.  This is to be expected since web end points will redirect users to secure port 443 as appropriate. Disabling port 80 would prevent normal functionality.

Added exceptions for all ELBs after confirming external ELBs also listen to 443. Internal ELBs are not required to listen to 443.

### CODE REVIEW

**Review by jonb-ifit — COMMENTED** [review]
Why are the ids in this list the same as the other list for `elb` (v1)?

**Comment by shanedroid** [comment]
assuming these exceptions were [pulled from the webui](https://github.com/nccgroup/ScoutSuite/wiki/Creating-and-Using-an-Exceptions-File), this made me think that perhaps scout suite sometimes incorrectly flagged/scanned classic <---> application elbs?

**Comment by timifit** [comment]
@jonb-ifit Thanks for catching the copy and paste.  Exceptions corrected and [verified](https://ifitdev.atlassian.net/browse/DEVOPS-1003?focusedCommentId=229051).

**Review by jonb-ifit — APPROVED** [review]
👍  LGTM

**Pull request merged**
