### PR TITLE
DEVOPS-991: Add ghub action workflow for deploying new docker images to ecr.

### PR DESCRIPTION
**Pull request by shanedroid**
[DEVOPS-991](https://ifitdev.atlassian.net/browse/DEVOPS-991): follow up for https://github.com/ifit/the-diagram/pull/745 to build and push docker images to ecr

### CODE REVIEW

**Review by timifit — COMMENTED** [review]
Everything looks OK.  My only concern is the fact that ECR lifecycle is based on last 3 versions created NOT last 3 approved/master versions.

In principle, with a slightly high volume of changes, you could end up rolling off the last approved master image before any 1 new PR is approved for merger to replace it.  Not sure of the probability of this occurring but probably not something you'd want to encounter by surprise.

**Comment by shanedroid** [comment]
> Everything looks OK. My only concern is the fact that ECR lifecycle is based on last 3 versions created NOT last 3 approved/master versions.
> 
> In principle, with a slightly high volume of changes, you could end up rolling off the last approved master image before any 1 new PR is approved for merger to replace it. Not sure of the probability of this occurring but probably not something you'd want to encounter by surprise.

short term/quick fix we could just push that higher than I agree 3 is slim 10 would be fine given how infrequently we merge changes into scoutsuite 🤞 

better fix would be to just have the [deployment workflow update the container ID in the ecs task definition](https://github.com/aws-actions/amazon-ecs-deploy-task-definition). This is trivial to setup, I was unsure of the best way to permit this drift with the [CFN template itself](https://github.com/ifit/the-diagram/blob/078db641fc0537eb09a2d86565b0bdbf9730de00/cloudformation/scout-suite.yml#L396-L426) since no tag is listed so the most recent `latest` tagged image would get used

**Review by timifit — APPROVED** [review]
I'm OK w/ a 10 image lifecycle. Definitely unlikely the active image would roll off with that many versions before rolling off.

**Comment by shanedroid** [comment]
> I'm OK w/ a 10 image lifecycle. Definitely unlikely the active image would roll off with that many versions before rolling off.

https://github.com/ifit/the-diagram/pull/754 👍

**Pull request merged**
